# Generated by Django 5.2.18 on 2026-10-10 13:28

from django.db import migrations


def copy_profiles_data(apps, schema_editor):
    """Copy every profile from oc_lettings_site, keeping their ids"""
    OldProfile = apps.get_model('oc_lettings_site', 'Profile')
    Profile = apps.get_model('profiles', 'Profile')

    for old_profile in OldProfile.objects.all():
        Profile.objects.create(
            id=old_profile.id,
            user=old_profile.user,
            favorite_city=old_profile.favorite_city,
        )


def delete_profiles_data(apps, schema_editor):
    """Undo the copy: empty the new table"""
    apps.get_model('profiles', 'Profile').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('oc_lettings_site', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.RunPython(copy_profiles_data, delete_profiles_data),
    ]
