# Generated by Django 5.2.18 on 2026-10-10 12:50

from django.db import migrations


def copy_lettings_data(apps, schema_editor):
    """Copy every address and letting from oc_lettings_site, keeping their ids"""
    OldAddress = apps.get_model('oc_lettings_site', 'Address')
    OldLetting = apps.get_model('oc_lettings_site', 'Letting')
    Address = apps.get_model('lettings', 'Address')
    Letting = apps.get_model('lettings', 'Letting')

    for old_address in OldAddress.objects.all():
        Address.objects.create(
            id=old_address.id,
            number=old_address.number,
            street=old_address.street,
            city=old_address.city,
            state=old_address.state,
            zip_code=old_address.zip_code,
            country_iso_code=old_address.country_iso_code,
        )

    for old_letting in OldLetting.objects.all():
        Letting.objects.create(
            id=old_letting.id,
            title=old_letting.title,
            address_id=old_letting.address_id,
        )


def delete_lettings_data(apps, schema_editor):
    """Undo the copy: empty the new tables"""
    apps.get_model('lettings', 'Letting').objects.all().delete()
    apps.get_model('lettings', 'Address').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),
        ('oc_lettings_site', '0001_initial')
    ]

    operations = [
        migrations.RunPython(copy_lettings_data, delete_lettings_data),
    ]
