# Generated by Django 5.2.18 on 2026-10-10 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0002_alter_profile_user'),
        ('lettings', '0002_copy_lettings_data_from_oc_lettings_site'),
        ('profiles', '0002_copy_profiles_data_from_oc_lettings_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letting',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Letting',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
